modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL= "https://github.com/GekidoLukas/showyouridentity/issues"
license = "GPL-3.0 license"

[[mods]]
modId = "showyouridentity"
version = "${version}"
displayName = "Show Your Identity"
authors = "GekidoLukas"
displayURL="https://www.gekidolukas.com"
description = '''
This mod aims to give players the ability to express their identity in any way they wish.
'''
logoFile = "assets/showyouridentity/icon.png"

[[dependencies.showyouridentity]]
modId = "forge"
mandatory=true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.showyouridentity]]
modId = "minecraft"
mandatory=true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.showyouridentity]]
modId = "architectury"
mandatory=true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "showyouridentity.mixins.json"
